version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=sua_chave_secreta_aqui
    volumes:
      - ./database.sqlite:/app/database.sqlite
    restart: unless-stopped